services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: rahasia
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse/ddl:/ddl